FROM mysql:5.7

# ROOT PASSWORD
#ENV MYSQL_ROOT_PASSWORD=r0o1

#ENV MYSQL_DATABASE=sampledb
#ENV MYSQL_USER=andre
#ENV MYSQL_PASSWORD=123456

#COPY schema.sql /docker-entrypoint-initdb.d/

#VOLUME /banco

EXPOSE 3306
# GRANT ALL PRIVILEGES ON * . * TO 'newuser'@'localhost';
# -v dados-do-banco:/var/lib/mysql
# docker run -d --name applic -p 3306:3306 --rm mysqlknex:1
# docker exec -it applic bin/bash
# docker run -it --name applic -p 3306:3306 -v /y/projects/Locacao/banco:/var/lib/mysql --rm mysqlknex:1